import { z } from 'zod';

import { SubnetSchema } from '../networks/types';

export type Instance = z.infer<typeof InstanceSchema>;

export const InstanceSchema = z.object({
  id: z.string(),
  openstack_server_id: z.string(),
  hostname: z.string(),
  reverse_dns: z.string(),
  size: z.string(),
  region: z.string(),
  network_id: z.string(),
  private_ip: z.string(),
  public_ip: z.string(),
  ipv6: z.string(),
  pseudo_ip: z.string(),
  template_id: z.string(),
  source_type: z.string(),
  source_id: z.string(),
  snapshot_id: z.string(),
  initial_user: z.string(),
  initial_password: z.string(),
  ssh_key: z.string(),
  ssh_key_id: z.string(),
  status: z.string(),
  notes: z.string(),
  firewall_id: z.string(),
  tags: z.array(z.string()),
  civostatsd_token: z.string(),
  civostatsd_stats: z.string(),
  civostatsd_stats_per_minute: z.array(z.string()),
  civostatsd_stats_per_hour: z.array(z.string()),
  openstack_image_id: z.string(),
  rescue_password: z.string(),
  volume_backed: z.boolean(),
  cpu_cores: z.number(),
  ram_mb: z.number(),
  disk_gb: z.number(),
  gpu_count: z.number(),
  gpu_type: z.string(),
  script: z.string(),
  created_at: z.string(),
  reserved_ip_id: z.string(),
  reserved_ip_name: z.string(),
  reserved_ip: z.string(),
  subnets: z.array(SubnetSchema),
});
