import { z } from 'zod';

export type Quota = z.infer<typeof QuotaSchema>;

export const QuotaSchema = z.object({
  id: z.string(),
  default_user_id: z.string(),
  default_user_email_address: z.string().email(),
  instance_count_limit: z.number(),
  instance_count_usage: z.number(),
  cpu_core_limit: z.number(),
  cpu_core_usage: z.number(),
  ram_mb_limit: z.number(),
  ram_mb_usage: z.number(),
  disk_gb_limit: z.number(),
  disk_gb_usage: z.number(),
  disk_volume_count_limit: z.number(),
  disk_volume_count_usage: z.number(),
  disk_snapshot_count_limit: z.number(),
  disk_snapshot_count_usage: z.number(),
  public_ip_address_limit: z.number(),
  public_ip_address_usage: z.number(),
  subnet_count_limit: z.number(),
  subnet_count_usage: z.number(),
  network_count_limit: z.number(),
  network_count_usage: z.number(),
  security_group_limit: z.number(),
  security_group_usage: z.number(),
  security_group_rule_limit: z.number(),
  security_group_rule_usage: z.number(),
  port_count_limit: z.number(),
  port_count_usage: z.number(),
  loadbalancer_count_limit: z.number(),
  loadbalancer_count_usage: z.number(),
  objectstore_gb_limit: z.number(),
  objectstore_gb_usage: z.number(),
  database_count_limit: z.number(),
  database_count_usage: z.number(),
  database_snapshot_count_limit: z.number(),
  database_snapshot_count_usage: z.number(),
  database_cpu_core_limit: z.number(),
  database_cpu_core_usage: z.number(),
  database_ram_mb_limit: z.number(),
  database_ram_mb_usage: z.number(),
  database_disk_gb_limit: z.number(),
  database_disk_gb_usage: z.number(),
});
